---
    - name: Install Apache (httpd)
      dnf:
        name: httpd
        state: present

    - name: Enable and start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Backup httpd.conf
      copy:
        src: /etc/httpd/conf/httpd.conf
        dest: /etc/httpd/conf/httpd.conf.bak
        remote_src: yes

    - name: Change Apache listen port to webserver_port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen {{ webserver_port }}'

    - name: Allow Apache to use webserver_port in SELinux
      command: semanage port -m -t http_port_t -p tcp {{ webserver_port }}
      args:
        warn: false
      ignore_errors: true

    - name: Ensure firewalld allows port 
      firewalld:
        port: "{{ webserver_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
        
    - name: task4 upload page
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
